### ISSUE TITLE
"error: 'PATH_MAX' undeclared" in GNU Hurd

### ISSUE THREAD

**Issue by changwoo** [libhangul/libhangul#24]
최근 Debian build 실패입니다.

https://buildd.debian.org/status/fetch.php?pkg=libhangul&arch=hurd-i386&ver=0.1.0%2Bgit20170815-1&stamp=1511811053&raw=0

https://www.gnu.org/software/hurd/community/gsoc/project_ideas/maxpath.html

위에 링크는 실제 사이즈에 맞춰서 동적 할당하는 좀 이상적인 방법을 얘기했는데 어렵고 실수하기도 쉬워서..  간단한 해결책은 정의되어 있지 않으면 이런 식으로 하나 고정값으로 정의하는 겁니다.

```
#ifndef PATH_MAX
#define PATH_MAX 4096
#endif
```

**Comment by cogniti** [comment]
`strcat()`로 대체하는 것은 어떨까요?

http://man7.org/linux/man-pages/man3/strcat.3.html

**Comment by cogniti** [comment]
아.. 제가 착각했네요..
strconcat, strjoin 같은 함수가 있으면 그걸로 대체하면 되고, 없으면 strlen, sizeof 를 이용하여 malloc 로 할당하면 PATH_MAX 를 대체할 수 있을 것 같습니다.

**Comment by cogniti** [comment]
PATH_MAX 가 사용된 함수가 2개가 있는데, 설정 파일이 저장되어 있는 디렉토리에서 키보드 파일을 읽어서 키보드를 추가하는 역할을 합니다.

따라서 `PATH_MAX`를 제거하고
`opendir()`, `readdir()` 함수로 파일 이름을 가져와서
`hangul_keyboard_new_from_file()`함수에 바로 넘겨 주는 것이 좋을 것 같습니다.

**Comment by choehwanjin** [comment]
여러 의견 감사합니다. 장기적으로는 PATH_MAX를 사용하지 않는 편이 좋을 것 같습니다.

**Comment by changwoo** [comment]
지금 어차피 inttypes.h 헤더를 사용하기 때문에 C99가 필수인데, C99가 된다면 스택에 variable length array 선언 가능합니다. 이런 식으로요.

```
char pattern[strlen(path) + strlen("/*.xml") + 1]
```

**Comment by choehwanjin** [comment]
코드를 수정하여 올렸습니다.

왠지  variable length array를 사용하면 좋지 않을 것 같은 느낌이랄까,
그런것 때문에 그냥 malloc으로 했습니다.
