### ISSUE TITLE
옛한글 입력기에서 방점을 입력할 방법이 있나요?

### ISSUE THREAD

**Issue by youknowone** [libhangul/libhangul#32]
조합 규칙을 좀 봤는데 방점 관련된 부분은 없는것 같더라고요. 혹시나 해서 문의드립니다.

이런 이슈가 있었습니다
https://github.com/gureum/gureum/issues/527#issuecomment-494457472

**Comment by choehwanjin** [comment]
옛한글 자판에 방점 키가 있으면 쉽게 입력이 가능하겠지만,  현재 libhangul에서 제공하는 옛한글 자판에는 방점이 키로 할당되어 있지 않습니다.
전에 구현했던 자판에는 방점이 있었습니다만, 옛한글 자판을 아래한글과 동일하게 맞추면서부터는 없어졌습니다. 참고: cb8c652a9eef94134c11474396a92335174a8b95

아래한글의 세벌식 옛한글 자판 U와 :에 배정되어 있는 · : 가 방점의 대용이 아닌가 하는 의심은 있습니다.
아마도 유니코드 시대 전에 자판이 만들어질때 저 기호를 방점 대신 쓰도록 설계했으나,
유니코드 시대에 들어서 방점으로 업그레이드를 못하지 않았나 생각합니다.

현재로서는 문자표를 이용하거나 유니코드로 직접 입력하는 다른 방법을 쓸 수 밖에 없을 것 같습니다.
방점은 유니코드 렌더러에서 Combining Character로 처리되어 알아서 조합되어 보일 것입니다.

**Comment by youknowone** [comment]
지금은 방법이 없는 것이군요. 설명 감사합니다.
