### ISSUE TITLE
한자(漢字) 목록의 오류 부분 수정 

### ISSUE THREAD

**Issue by studioego** [libhangul/libhangul#36]
libhangul의 한자(漢字) 목록에서 오류가 몇가지 보이고 있습니다.

https://github.com/libhangul/libhangul/blob/master/data/hanja/hanja.txt

1. `나우:老撾:라오스`

`老撾`의 음은 `노과`이며, `나우`가 아닙니다.
이 문제는 MS사 윈도우에서 실수로 들어간 오타로 보이며, `노과`로 수정해야합니다

출처1: https://twitter.com/sai_Eoneo/status/1154661300565209088
출처2: https://twitter.com/studioego/status/1154680124534448133
출처3: https://twitter.com/sai_Eoneo/status/1154682367119785984

네이버 한자사전의 `老撾`링크: https://hanja.dict.naver.com/search?query=%E8%80%81%E6%92%BE

2. `퐁:乓:`

`乓`의 음은 `팡`입니다

`물건을 부딪치는 소리 병, 물건을 부딪치는 소리 팡`

출처: https://hanja.dict.naver.com/hanja?q=%E4%B9%93

이외에도 한자(漢字) 목록에 오류가 보이고 있습니다.

수정사항에 대하여 수정 정리 및 커밋하면 이슈 닫겠습니다.
커밋완료되면 리뷰 부탁드립니다.

**Comment by choehwanjin** [comment]
노과와 나우가 뒤바뀌어 작성된 것 같습니다.

```
... 
나우:老撾:라오스
...
노과:羅宇:라오스
...
```

 乓은 팡으로 바꾸는 것이 맞겠습니다.

**Comment by studioego** [comment]
이슈 반영을 해주셔서 감사합니다. 이슈를 닫겠습니다.
