### ISSUE TITLE
한자(漢字) 목록 중 ㄱ-곶까지의 내용 수정 

### ISSUE THREAD

**Issue by studioego** [libhangul/libhangul#39]
한자 목록 확인 중, 여러 낱말에서 한자음이 중간에 누락되거나 중복된걸 확인하였습니다.

* 네이버 국어사전 https://ko.dict.naver.com
* 다음 국어사전 https://dic.daum.net/index.do?dic=kor
* 표준국어대사전  http://stdict.korean.go.kr 

위의 사전 자료를 토대로 몇몇 부분 수정하였습니다.

내용은 PR내용을 확인해보시기 바랍니다.

**Comment by choehwanjin** [comment]
작업이 완료되었으므로 닫겠습니다. (2c9ddb333d57c274de2b4e7fd18f78d5bbf96c7d)
