### ISSUE TITLE
Fails to build if config.rpath doesn't exist

### ISSUE THREAD

**Issue by emersion** [libhangul/libhangul#43]
`touch config.rpath` fixes it.

**Comment by majecty** [comment]
autogen.sh에 이 내용을 추가하면 어떨까요?

**Comment by choehwanjin** [comment]
이 이슈는 #34 와 같은 것입니다.
intltool을 사용해서 발생한 것 같은데요, intltool을 제거하고 gettext를 사용하는 Pull Request #35 적용으로 해결이 됩니다.

**Comment by choehwanjin** [comment]
별다른 이슈가 없다면 #35 로 해결된 것으로 알고 이 이슈는 닫겠습니다.
