### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by wolyosung** [libhangul/libhangul#47]
ubuntu 18.04에서 빌드시 다음과 같은 이슈가 있었습니다.

'%'-style pattern rules are a GNU make extension 이라는 오류 메시지가 출력됩니다.
이를 해결하기 위해서는 제공된 파일 내의 configure.ac 파일 안에 AM_INIT_AUTOMAKE([-Wno-portability])를 추가해줘야 빌드가 됩니다.

**Comment by choehwanjin** [comment]
제가 확인해보니까 config.rpath 관련 에러가 나는 것 같은데요.
-Wno-portability 옵션 관련한 것은 워닝이라서 저게 없어도 빌드가 됩니다.
혹시 에러 메시지 확인 가능하시면 확인 부탁드립니다.

**Comment by wolyosung** [comment]
앗 안녕하세요 하도 옛날에 봤던 거라서 지금 환경이 바뀌었군요..
다음에 확인해보고 혹시 변동 있으면 여기다 올려 놓겠습니다.

**Comment by choehwanjin** [comment]
이 이슈도 #34 , #43 과 같은 원인으로 발생한 문제일 것 같습니다.
cmfog.rpath 문제는 #35 로 해결이 되었을 것 같습니다.

**Comment by choehwanjin** [comment]
별다른 이슈가 없다면 #35 로 해결된 것으로 알고 이 이슈는 닫겠습니다.
